### ISSUE TITLE
Define "asm.js integer literal" once and use the name throughout the spec

### ISSUE THREAD

**Issue by jruderman** [asm-js/validator#57]
- The "does not contain a . character" requirement is weird. Bytecode might not include this information. This choice could use some explanation.
- The phrase "does not contain a . character" occurs many times in the spec.
- Some places forget to require that it's an integer, e.g. http://asmjs.org/spec/latest/#caseclause seems to allow 1e-3 (no dots, but also not an integer).

**Comment by matthewhill** [comment]
On the face of it, this may seem like a minor issue, but it is actually quite pernicious. Observe that representing a numeric literal—whose source contains a negative exponent, but not a `.` character—by an integer type may introduce a loss in precision. (_May_ because there is no such loss for, e.g., `1e-0`.) It follows that AOT compilation may affect the observational behaviour of JavaScript code, which is contrary to the intentions of asm.js. Consider, for example, the following valid module:

```javascript
function M() {
  "use asm"
  function f() {
    return 1e-3
  }
  return f
}
```
Now, without AOT compilation, `M()()` yields `0.001`, but with AOT compilation, it yields `0`. Hence, a more sophisticated procedure for deciding how to represent a numeric literal is required. In particular, a procedure that satisfies the following conditions would avoid the aforementioned bug:

> `n` resolves to an integer representation &nbsp; &nbsp; ⇒ &nbsp; &nbsp; MV(`n`) is an integer
> `n` resolves to a floating point representation &nbsp; &nbsp; ⇐ &nbsp; &nbsp; the source of `n` contains a `.` character

where MV( · ) is defined in section 11.8.3.1 of ECMA-262/6.

**Comment by kripken** [comment]
Nice find, that's a bug that went unnoticed I guess.
